/*
 *	Copyright (c) 2013, Nenad Markus
 *	All rights reserved.
 *
 *	This is an implementation of the algorithm described in the following paper:
 *		N. Markus, M. Frljak, I. S. Pandzic, J. Ahlberg and R. Forchheimer,
 *		Object Detection with Pixel Intensity Comparisons Organized in Decision Trees,
 *		http://arxiv.org/abs/1305.4537
 *
 *	Redistribution and use of this program as source code or in binary form, with or without modifications, are permitted provided that the following conditions are met:
 *		1. Redistributions may not be sold, nor may they be used in a commercial product or activity without prior permission from the copyright holder (contact him at nenad.markus@fer.hr).
 *		2. Redistributions may not be used for military purposes.
 *		3. Any published work which utilizes this program shall include the reference to the paper available at http://arxiv.org/abs/1305.4537
 *		4. Redistributions must retain the above copyright notice and the reference to the algorithm on which the implementation is based on, this list of conditions and the following disclaimer.
 *
 *	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *	IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */


#include "opencv2/opencv.hpp"
using namespace cv;

#include <cstdio>
#include <iostream>
#include <stdint.h>
using namespace std;

#include "picornt.hpp"

namespace pico {

// autogenerated
#include "facefinder.c"

float getOverlap(float r1, float c1, float s1, float r2, float c2, float s2)
{
	float overr = MAX(0, MIN(r1+s1/2, r2+s2/2) - MAX(r1-s1/2, r2-s2/2));
	float overc = MAX(0, MIN(c1+s1/2, c2+s2/2) - MAX(c1-s1/2, c2-s2/2));
	return overr*overc / (s1*s1+s2*s2-overr*overc);
}

void ccdfs(vector<int> &a, int i, vector<Vec4f> &obj)
{
	for (size_t j=0; j<obj.size(); ++j)
    {
        if (a[j]!=0)
            continue;
        if (getOverlap(obj[i][1],obj[i][2],obj[i][3], obj[j][1],obj[j][2],obj[j][3])<=0.3f)
            continue;

		a[j] = a[i];
		ccdfs(a, j, obj);
    }
}


int findConnectedComponents(vector<int> &a, vector<Vec4f> &obj)
{
	int cc = 1;
	for (size_t i=0; i<obj.size(); ++i)
    {
		if (a[i] == 0)
		{
			a[i] = cc++;
			ccdfs(a, i, obj);
		}
    }
	return cc-1;
}

int clusterDetections(vector<Vec4f> &obj)
{
    vector<int> a(obj.size(),0);
	int ncc = findConnectedComponents(a, obj);
	if (! ncc) return 0;

	int idx = 0;
	for (int cc=1; cc<=ncc; ++cc)
	{
        Vec4f sum(0,0,0,0);
		int k = 0;
		for (size_t i=0; i<obj.size(); ++i)
        {
			if (a[i] == cc)
			{
				sum += obj[i];
                k++;
			}
        }
		obj[idx++] = Vec4f(sum[0], sum[1]/k, sum[2]/k, sum[3]/k); // sum[0] is accumulated confidence measure
	}
    obj.resize(idx);
    return idx;
}


int findObjects(const Mat &img, vector<Vec4f> &obj, float threshold,
			    float scalefactor, float stridefactor, float minsize, float maxsize)
{    
    for (float s=minsize; s <= maxsize; s*=scalefactor)
    {
	    float r, c, dr, dc;
	    dr = dc = MAX(stridefactor*s, 1.0f);
	    for (r=s/2+1; r<=img.rows-s/2-1; r+=dr)
        {
		    for (c=s/2+1; c<=img.cols-s/2-1; c+=dc)
		    {
			    float q=0;
                if (run_facefinder(&q, int(r), int(c), int(s), img.data, img.rows, img.cols, img.cols) == 1)
			    {
				    if (q>threshold)
				    {
                        obj.push_back(Vec4f(q,r,c,s));
				    }
			    }
		    }
        }
    }
	if (! obj.empty())
        return clusterDetections(obj);
    return 0;
}
}; // pico



