all:
	echo "hi"
#	tar -czf ocv.tgz ocv

#all: ocv z2z2_ocv
#
#ocv:
#	
#z2z2_ocv:
#	g++ birds.cpp myapp.cpp -Iocv/include -Locv/lib  -lrt -lpthread -lz -ljpeg -lpng -ltiff -ljasper -lopencv_highgui -lopencv_imgproc -lopencv_core  -o z2z2
