# -*- coding: utf-8 -*-
"""cv2_cuda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NFv0seCnNr01XnGZlfEDL6BbkA-ISY-I
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/opencv/opencv
!git clone https://github.com/opencv/opencv_contrib
!mkdir /content/build
# %cd /content/build

!cmake -DOPENCV_EXTRA_MODULES_PATH=/content/opencv_contrib/modules  \
       -DBUILD_SHARED_LIBS=OFF \
       -DBUILD_TESTS=OFF \
       -DBUILD_PERF_TESTS=OFF \
       -DBUILD_EXAMPLES=OFF \
       -DWITH_OPENEXR=OFF \
       -DWITH_CUDA=ON \
       -DWITH_CUBLAS=ON \
       -DWITH_CUDNN=ON \
       -DOPENCV_DNN_CUDA=ON \
       /content/opencv

!make -j8 install

import cv2
cv2.__version__

!ls -l

!cp  -r /content/build/lib   "/content/drive/My Drive/cv2_cuda"
!cp  /content/build/lib/python3/cv2.cpython-37m-x86_64-linux-gnu.so   "/content/drive/My Drive/cv2_cuda"
!cp -r /usr/include/opencv2 "/content/drive/My Drive/cv2_cuda"

!cp "/content/drive/My Drive/cv2_cuda/cv2.cpython-37m-x86_64-linux-gnu.so" .

!wget  https://github.com/opencv/opencv/raw/master/samples/dnn/human_parsing.py
!wget "https://www.dropbox.com/s/qag9vzambhhkvxr/lip_jppnet_384.pb?dl=0" -O lip_jppnet_384.pb

!python human_parsing.py -i=/person.jpg -m=lip_jppnet_384.pb -b=4

import cv2 as cv
from google.colab.patches import cv2_imshow
    
img = cv.imread("output.png")
cv2_imshow(img)