# -*- coding: utf-8 -*-
"""cyclegan_face.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xCQ9MSacpJFCc0fB_TYWdtor-qSnLP4C
"""

!git clone https://github.com/hyunbo9/yonsei

# Commented out IPython magic to ensure Python compatibility.
# %cd yonsei
!ls -l

f1 = open("module.py", "rb")
txt = f1.read()
f1.close()
txt = txt.replace(b"scipy.misc", b"imageio")
f2 = open("module.py", "wb")
f2.write(txt)
f2.close()

!python model.py

import scipy
import imageio
help(imageio.imread)