# -*- coding: utf-8 -*-
"""fawkes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VZiAUSr3mWCizQA5ExNy-iG86-L7_lhj
"""

!pip install tensorflow==1.14.0
!pip install keras==2.2.5

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Shawn-Shan/fawkes
# %cd fawkes

!wget http://sandlab.cs.uchicago.edu/fawkes/files/low_extract.h5
!wget http://sandlab.cs.uchicago.edu/fawkes/files/low_extract_emb.p.gz
!wget http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz

import tensorflow as tf
from fawkes import Fawkes

protector = Fawkes("low_extract", False, 1)

!ls
import os
os.path.expanduser('~')

!whoami"

import keras
import keras.backend as K
import numpy as np
import tensorflow as tf

#print(protector)
model = keras.models.load_model("/content/fawkes/low_extract.h5")
print(model)

def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a pruned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    pruned so subgraphs that are not necessary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    from tensorflow.python.framework.graph_util import convert_variables_to_constants
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        # Graph -> GraphDef ProtoBuf
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph



K.set_learning_phase(0)
print(model.inputs)
print(model.outputs)
    
frozen_graph = freeze_session(K.get_session(),
                              output_names=[out.op.name for out in model.outputs])
tf.train.write_graph(frozen_graph, ".", "tf_test.pb", as_text=False)

!ls -l

import cv2
from google.colab.patches import cv2_imshow

net = cv2.dnn.readNet("tf_test.pb")
#inp = np.ones((1,3,224,224),np.float32)
im = cv2.imread("/content/fawkes/0000b3af.png")
cv2_imshow(im)
inp = cv2.dnn.blobFromImage(im,1,(224,224))
net.setInput(inp)
res = net.forward()
print(res.shape)
"""net.dumpToFile("fawkes_ext.dot")
!dot fawkes_ext.dot -Tpng -ofawkes_ext.png
#!head -c 5000 pose_dot.png
im=cv2.imread("fawkes_ext.png")
print(np.shape(im))
"""
im = res.reshape(32,32)
cv2_imshow(im*255)