# -*- coding: utf-8 -*-
"""GANSketching.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTQ9yrAPplTr3Ap1tOKI_-JFUTEVZzpd
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/PeterWang512/GANSketching
# %cd GANSketching

!sh /content/GANSketching/weights/download_weights.sh

pip install ninja

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/GANSketching
!python generate.py --ckpt /content/GANSketching/weights/by_author_cat_aug.pth

!ninja

import torch
torch.__version__