# -*- coding: utf-8 -*-
"""goturn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ULYzzLl46S3mhahiUus3qvmzIpndeZPw
"""

!pip install opencv-contrib-python==4.1.2.30
#!pip install opencv-contrib-python==3.4.8.29

# Commented out IPython magic to ensure Python compatibility.
!git clone --depth=1 https://github.com/spmallick/goturn-files 
# %cd goturn-files 
!cat goturn.caffemodel.zip* > goturn.caffemodel.zip
!unzip goturn.caffemodel.zip
!ls -l
#%cd ..

import cv2, numpy as np
#%cd goturn-files
tracker = cv2.TrackerGOTURN_create()  

frame = np.ones((100,100,3),dtype=np.uint8)
bbox = (30,30,40,40)

ok = tracker.init(frame,bbox)
print("tracker.init",ok)

import cv2, numpy as np
!ls -l
net = cv2.dnn.readNet("goturn.caffemodel", "goturn.prototxt")