# -*- coding: utf-8 -*-
"""human_parsing2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gg2lnJY_2IeHH2nQTxHtPT7AFD-VW5PW
"""

!pip install opencv-python==4.2.0.34

import cv2
cv2.__version__

!wget  https://github.com/opencv/opencv/raw/master/samples/dnn/human_parsing.py
!wget "https://www.dropbox.com/s/qag9vzambhhkvxr/lip_jppnet_384.pb?dl=0" -O lip_jppnet_384.pb

!python human_parsing.py -i=person.jpg -m=lip_jppnet_384.pb


"""
Traceback (most recent call last):
  File "human_parsing.py", line 178, in <module>
    output = parse_human(image, args.model, args.backend, args.target)
  File "human_parsing.py", line 150, in parse_human
    output = run_net(input, model_path, backend, target)
  File "human_parsing.py", line 69, in run_net
    net = cv.dnn.readNet(model_path)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:1939: error: (-213:The function/feature is not implemented) Unsupported mode of reduce_mean operation. in function 'populateNet'
"""