# -*- coding: utf-8 -*-
"""stylegan2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12xKz1zwUJw5qmJE8t2YVPrlDbk4-CDUD
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/NVlabs/stylegan2
# %cd stylegan2

# Generate uncurated ffhq images (matches paper Figure 12)
!python run_generator.py generate-images --network=gdrive:networks/stylegan2-ffhq-config-f.pkl \
  --seeds=6600-6625 --truncation-psi=0.5