# -*- coding: utf-8 -*-
"""yolov7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n1p93RkhXh6_-6vJMJ56ie_XgIRzrl4Z
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/jinfagang/yolov7
# %cd yolov7

pip install alfred-py

#pip install detectron2
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

pip install onnx

# Commented out IPython magic to ensure Python compatibility.
# %cd weights
!sh get_models.sh
# %cd /content/yolov7

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov7 
!python demo.py --config-file configs/coco/sparseinst/sparse_inst_r50vd_giam_aug.yaml --video-input ~/Movies/Videos/86277963_nb2-1-80.flv -c 0.4 --opts MODEL.WEIGHTS weights/sparse_inst_r50vd_giam_aug_8bc5b3.pth
#!python3 export.py --config-file detr/config/file --output my.png --input ./images/COCO_val2014_000000002153.jpg 
#!python3 export.py --config-file configs/coco/sparseinst/sparse_inst_r50_giam_aug.yaml --output my.png --input ./images/COCO_val2014_000000002153.jpg --opts MODEL.WEIGHTS /content/yolov7/weights/sparse_inst_r50_giam_aug_2b7d68.pth

!wget https://github.com/jinfagang/yolov7/raw/main/configs/coco/sparseinst/sparse_inst_r50_dcn_giam_aug.yaml
!wget https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/resnet50d_-464e36ba.pth

!ls -l

import cv2
print(cv2.__version__)

nn = cv2.dnn.readNet("/content/yolov7/weights/sparse_inst_r50_giam_aug_2b7d68.onnx")

!cp "/content/drive/My Drive/cv2_cuda/cv2.cpython-37m-x86_64-linux-gnu.so" .